### ISSUE TITLE
Does the model only support input images with the same width and height?

### ISSUE THREAD

**Issue by sangenan** [saic-vul/image_harmonization#2]
when I run predict_for_dir.py and modify resize=-1, mode use :HRNet32 + iDIH256

code running error:

```
Traceback (most recent call last):
  File "scripts/predict_for_dir.py", line 106, in <module>
    main()
  File "scripts/predict_for_dir.py", line 59, in main
    pred = predictor.predict(image, mask)
  File "./iharm/inference/predictor.py", line 32, in predict
    predicted_image = self.net(image, mask)['images']
  File "/home/sangenan/anaconda3/envs/torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "./iharm/model/backboned/ih_model.py", line 85, in forward
    output = self.model(image, mask, backbone_features)
  File "/home/sangenan/anaconda3/envs/torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "./iharm/model/base/dih_model.py", line 29, in forward
    output = self.decoder(intermediates, image, mask)
  File "/home/sangenan/anaconda3/envs/torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "./iharm/model/modeling/conv_autoencoder.py", line 93, in forward
    output = output + skip_output
RuntimeError: The size of tensor a (44) must match the size of tensor b (45) at non-singleton dimension 2
```

**Comment by ksofiyuk** [comment]
Height and width may be different, but both should be divisible by 128. However, it is not a limitation of our approach, we just implemented the simplest configuration for 256x256 images. You can easily modify the network architecture that supports inputs with any resolution (you should add torch.interpolate for a tensor before summing or concatenating).

**Comment by sangenan** [comment]
Thanks, I have successfully modified the network and re-trained

**Comment by tachikoma777** [comment]
is it possible to generate a larger output without modify the network?
I tried to change -- resize 256 to 2560 but the output is not good.

**Comment by ksofiyuk** [comment]
Technically it is possible, but you will get significantly worse results as the pre-trained models were not trained for this setup. To achieve good quality on high resolution images you should train a new model using, for instance, the `crop512` augmentation scheme (you can find examples of these configs [here](https://github.com/saic-vul/image_harmonization/tree/master/models/crop512)).

**Comment by coallar** [comment]
> -- resize 256

Hi，Bro, how do you solve this problem?
